### ISSUE TITLE
Question on commit "Patched bid128_hypot()"

### ISSUE THREAD

**Issue by fmartinp** [thomasokken/free42#28]
Hi Thomas,
Do you know if this patch can be applied directly in the compiltation of Free42 for DM42? Or is not possible because the Intel Library is preloaded in a different part of the memory of DM42?
I am asking that because I am doing my own compilation of Free42 for my DM42 and I am not sure how to implement this change in the code. Actually, I do not see that the patch files are involved in the DM42 compilation.
Thanks in advance.

**Comment by thomasokken** [comment]
So you are building Free42 for the DM42, but are using a pre-built Intel library, is that correct?
If that is the case, do they not provide the scripts for builting the library yourself?

**Comment by fmartinp** [comment]
Hi Thomas,

Yes, I am just updating the library libfree42_bcd_rel.a using your code. However, they provide directly the compiled intel decimal library for the generation of the actual binary to be uploaded in the calculator, the so called DM42PGM. See the folder below:
https://github.com/swissmicros/DM42PGM/tree/master/lib

I was looking in this makefile if it can be used to create the intel library : https://github.com/swissmicros/free42/blob/master/console/Makefile

However, I have read in some forums that the intel library is already preloaded in the memory of the calculator in an area called QSPI. So, I am not sure that even if I manage to compile the intel library it will help.

Fernando



Regards,
Fernando

**Comment by thomasokken** [comment]
As fas as I remember, a QSPI update is a separate step from uploading the rest of flash, but you should be able to build and install everything yourself, including the QSPI part. I can't help with that, though, since I'm not familiar with the process myself.
If you don't want to deal with that, you could just apply the work-around for Phloat::hypot() instead, the one that I used in the 3.0.1 release, before I rolled it back and fixed the problem by patching the Intel library.

**Comment by fmartinp** [comment]
Thanks for the answer. I will try to find some information on how to build and update the QSPI. I did not succeed the last time that I tried to find that information.

So probably I will end up with your work-around.

Thanks!
