### ISSUE TITLE
A separated repository for IntelRDFPMathLib with ARM support?

### ISSUE THREAD

**Issue by wdhwg001** [thomasokken/free42#31]
Hi,

I've been searching for a working patch to make IntelRDFPMathLib support ARM architectures for a long time, and thanks a lot for the hard work on these patches!

As there might be others looking for a working IntelRDFPMathLib on ARM architectures, it would be really great if we could have a self-maintained IntelRDFPMathLib repository so that it could support arm architectures on Linux, Android, macOS and iOS without applying patches for each of them.

**Comment by thomasokken** [comment]
The test suite errors are all in various format conversion functions. The exact set of functions that fails is slightly different between the Android, iOS, and MacOS ARM builds. The fact that it's all in conversion functions suggests that the issues are all related to struct alignment differences and things like that.

(You can run the test suite in Free42 by creating a debug build of Free42 itself and then executing the FPTEST function. The test output is written to the console.)

**Comment by thomasokken** [comment]
I'm putting this on my long-term to-do list.
I won't be working on this any time soon, and closing the issue for now.

**Comment by thomasokken** [comment]
I looked into the test failures on ARM, and found that they can be fixed by adding

-fsigned-char -DBID_SIZE_LONG=8

to the C compiler flags for 64-bit ARM, and

-fsigned-char -DBID_SIZE_LONG=4

for 32-bit ARM.

The only remaining issues after applying these fixes is that the conversion functions to and from binary80 still don't work on MacOS and iOS; this is due to missing support for 'long double' in Apple's compiler. The Linux and Android builds don't have this problem.

I haven't tried building the library and Free42/Plus42 for Windows on ARM yet, but once I have that sorted out, I'll try to create a proper patch for the library and contribute that to Intel and/or Netlib.
