### ISSUE TITLE
Qt/QML version for Sailfish/Jolla

### ISSUE THREAD

**Issue by sbridger** [thomasokken/free42#33]
This is not a request I seriously expect you to undertake or even consider, but you have commented elsewhere about making a qt/qml version for your own learning purposes.

Sailfish phone is qt/qml based, so it would be better than pointless to do it for sfos.
Or perhaps if you were doing a qt version, there might be help to complete it for SFOS.

**Comment by thomasokken** [comment]
I do still have a port to Qt on my to-do list, but since I already have the big five platforms covered, I do consider it a learning exercise, low priority. Of course once I get started on it, it may not actually take a huge amount of effort... I am curious how closely the app's look and feel on each platform will match that of the native versions, and how much effort it will take to deal with the fixed window sizes on Android and iOS. I guess I'll find out when I get around to it!
