### ISSUE TITLE
Use CI for artifacts/nightly builds

### ISSUE THREAD

**Issue by rogersachan** [thomasokken/free42#4]
Using a free CI like appveyor or azure pipelines would allow for artifacts of builds with each commit made.

**Comment by thomasokken** [comment]
I am skeptical. Allow me to explain why --

My release process consists of these steps:

(on the Mac)
cd ~/free42
git pull
sh ./build-mac
sh ./build-android
sh ./build-history

(on the Windows VM)
cd ~/free42
git pull
sh ./build-windows
scp packages/* mymac:free42/packages

(on the Linux VM)
cd ~/free42
git pull
sh ./build-gtk
scp packages/* mymac:free42/packages

(back on the Mac)
run FileZilla
copy ~/free42/packages/Free42Mac.zip -> public_html/free42/download
copy ~/free42/packages/Free42Android.apk -> public_html/free42/download
copy ~/free42/packages/Free42Windows.zip -> public_html/free42/download
copy ~/free42/packages/Free42Linux.tgz -> public_html/free42/download
copy ~/free42/packages/free42-macports-${VERSION}.tgz -> public_html/free42/upstream
copy ~/free42/packages/free42-nologo-${VERSION}.tgz -> public_html/free42/upstream
copy ~/free42/packages/history.html -> public_html/free42
copy ~/free42/packages/index.html <- public_html/free42
Update version number in index.html; note that this isn't always a simple matter of replacing the old version number with the new, since not all platforms are always at the same version -- if I fix a bug in the Android shell, for example, I typically won't release new builds for the other platforms, since they are not affected
copy ~/free42/packages/index.html -> public_html/free42

Login to https://play.google.com/apps/publish/
Upload ~/free42/packages/Free42Android.apk and create a new release

Run Xcode
File -> Open Recent -> Free42.xcodeproj -- iphone
Scheme Selector -> Generic iOS Device
Product -> Archive
Organizer -> Distribute App
[...]
Login to https://itunesconnect.apple.com/ and create a new release

I'm sure some of those steps could be automated, but most of the hassle lies in uploading the builds to my web site, the Google Play Store, and the iOS App Store; pretty much all of the rest is handled by the build-XXX scripts.

**Comment by rogersachan** [comment]
I feel that it could be useful up to the linux part. My initial goal for this would have this set up so that people could test out nightly builds and avoid issues like #2 .

**Comment by thomasokken** [comment]
That's an issue that's specific to the MacOS and iOS builds, though. Also, the very notion of "nightly builds" implies some sort of discipline regarding commits that doesn't actually exist. 😄 When I put out a release, there has been at least some testing, although often not enough... but between releases, anything goes, including commits that break certain builds. I think if someone is adventurous enough to want to run the latest from this repo, they should build it themselves.
In a more professional setting, of course I'd use branches for development and only merge release- or beta-quality code into master, but for a one-person spare-time project like this, that kind of discipline is probably not going to happen.
