### ISSUE TITLE
Minimal documentation to study sources

### ISSUE THREAD

**Issue by daitangio** [thomasokken/free42#51]
Hi, 
 first of all thank you for writing free42!
I am digging in the source code to study how it works, for my personal interest and to play a bit with the code.
Can you give me some insight on how to implement a new "shell".
I mean, as far as I can understand there is the core libraries, and then the gtk/android/windows versions implement a set of functions declared inside files called shell_*.h
Where can I find some comment explaining the overall structure? 
I will be happy to produce a small markdown file to collect all the information I can find out.
I only need some overview to start with.
Thank you!

**Comment by thomasokken** [comment]
The most important files to look at are shell.h and core_main.h. The shell.h file declares the shell functions that are called by the core, and core_main.h declares the core functions that are called by the shell (and a few other things, after line 332).

There is no documentation on the core/shell interface beyond those two files, but it should be enough to get started. The architecture is pretty straightforward: the shell reports keystrokes to the core and the core responds by painting the display. The tricky parts are the behavior of keys that are held down, and how the core requests and yields the CPU when running programs.

I don't feel like writing documentation beyond what already exists. I think studying the GTK or Windows shells is the best way to get started, since they best reflect the original, purely procedural architecture.

I'll be happy to answer any questions, just contact me via email!

**Comment by axd1967** [comment]
Just a note for the future...

Ideally everything relating to (awesome) user oriented documentation (found at https://thomasokken.com/free42/) should live in the repository, and evolve whenever code evolves (especially by passing via branches first), rather than being maintained outside of the repository; because now,  user documentation impacted by code changes must be updated outside of the repository too, while the branch containing the code changes could easily contain the doc changes, even if the branch is never merged to `master`: it is ready to merge, and user docs are instantly updated.

https://pages.github.com/ might be a solution, but no guarantee that it is future proof... The current approach, a separate website, might be better, but when that site disappears for good, the code will remain behind, scattered across clones, without decent user documentation.

Ideally, the entirety of file artefacts should live in the repo, and only there. 

(That's why the wiki component of Github is not a good idea either, as it lives in a separate repo.)

A good alternative is the Markdown feature of GitHub: this allows to publish user documentation as almost normal web pages.

But this is far too big to tackle; maybe for a next project.
